### ISSUE TITLE
Some data quality incidents are empty

### ISSUE THREAD

**Issue by sztuka-billtech** [dqops/dqo#21]
After running daily partition checks, DQOps tends to create empty data quality incidents that have no issues. I could not find a root cause for this, it seems to appear randomly (around 10% of all reported incidents).

![image](https://github.com/dqops/dqo/assets/141846766/18842ed5-a3e8-4660-89ce-b86b092bcf8b)

After checking the DevTools, it seems like the API is sending an empty issue list.
![image](https://github.com/dqops/dqo/assets/141846766/b4b428f7-9fe6-4d60-951b-680ab2e316be)

Steps to reproduce:
 1. Add a few hive-partitioned tables to a single data source (S3, parquet file format)
 2. Set up Daily partition checks for those tables (some are templated by column name - tables have the same schema, some tables have overriden template rule values)
 3. Batch run daily partition check for a 45-day time period

Bug encountered in versions: 
- release v1.2.0
- develop commit hash: dfb42f16

**Comment by dqops** [comment]
This problem is related to the default time window used in the filters to load incidents for recent months. If a data quality issue is related to a very old daily partition, it is not shown.
The version 1.3.0 fixes filters and aligns the filters used to create incidents with the filters to load results to show in UI.
