### ISSUE TITLE
Cannot navigate checks menu via permalinks

### ISSUE THREAD

**Issue by sztuka-billtech** [dqops/dqo#25]
Pasting the following link `dqops/partitioned/connection/my_conn/schema/my_schema/table/my_table/monthly` does not lead to desired page, but drops the user at the last open tab in the checks view

Observed in develop #db1e1d4a

**Comment by dqops** [comment]
Direct access to all sections of the application from permalinks is a nice-to-have feature that we have planned in the backlog. It will be released gradually for all sections because opening a section also requires expanding the navigation tree and selecting tabs. 
For the moment, permalink support is limited to incidents for which we generate permalinks in the notification messages.

**Comment by dqops** [comment]
Closing, it is a feature request.
